from enum import StrEnum


class MsgType(StrEnum):
    HELLO = "HELLO"
    CAPABILITY_ADVERTISE = "CAPABILITY_ADVERTISE"
    CAPABILITY_QUERY = "CAPABILITY_QUERY"
    PROTOCOL_MAP = "PROTOCOL_MAP"
    INVOKE = "INVOKE"
    RESULT = "RESULT"
    ERROR = "ERROR"
    MEMORY_PUT = "MEMORY_PUT"
    MEMORY_QUERY = "MEMORY_QUERY"
    STATE_REF = "STATE_REF"
    TRACE_EVENT = "TRACE_EVENT"
